name: Deploy SAM Backend

on:
  push:
    branches:
      - master
    paths:
      - 'middleware/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Deploy Backend with SAM CLI
      run: |
        cd middleware
        pip install -r ./requirements.txt  --target ./python
        chmod 755 ./python
        zip -r python-site-packages.zip python
        rm -r python
        sam build
        sam deploy --parameter-overrides CORS_ORIGIN=${{ secrets.CORS_ORIGIN }} R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }} R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }} R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
        rm python-site-packages.zip

      env:
        AWS_DEFAULT_REGION: us-east-2
